name: postgres

services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres:
    external: true
